name: Get Current Vaccination Centers

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 2 days at 9:00 AM
    # Time specfied here is in UTC format
    - cron: '30 3 */2 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: install dependencies
        run: pip install -r requirements.txt
      
      - name: execute python script
        env:
          DISTRICT_ID: ${{ secrets.DISTRICT_ID }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_RECIPIENT_USER_NAME: ${{ secrets.TWITTER_RECIPIENT_USER_NAME }}
        run: python main.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "runs script" -a
      - name: push new README
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
