name: Get Current Vaccination Centers

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: install dependencies
        run: pip install -r requirements.txt
      
      - name: execute python script
        run: python main2.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update readme" -a
      - name: push new README
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
